from __future__ import annotations

from ._types import ImuDict, JointCmdDict, JointDataDict

class RobotCmd:
    """Mutable command buffer for the 12 Lite3 joints."""

    def __init__(self) -> None: ...
    def zero(self) -> None: ...
    def set_joint(
        self,
        index: int,
        position: float,
        velocity: float,
        torque: float,
        kp: float,
        kd: float,
        /,
    ) -> None: ...
    def set_leg(
        self,
        side: str,
        position: float,
        velocity: float,
        torque: float,
        kp: float,
        kd: float,
        /,
    ) -> None: ...
    def set_all(
        self,
        position: float,
        velocity: float,
        torque: float,
        kp: float,
        kd: float,
        /,
    ) -> None: ...
    def joint(self, index: int, /) -> JointCmdDict: ...
    def joints(self) -> list[JointCmdDict]: ...
    def copy(self) -> RobotCmd: ...


class RobotData:
    """Snapshot of one Lite3 robot-state packet."""

    def __init__(self) -> None: ...
    def tick(self) -> int: ...
    def set_tick(self, tick: int, /) -> None: ...
    def imu(self) -> ImuDict: ...
    def set_imu(
        self,
        timestamp: int,
        angle_roll: float,
        angle_pitch: float,
        angle_yaw: float,
        angular_velocity_roll: float,
        angular_velocity_pitch: float,
        angular_velocity_yaw: float,
        acc_x: float,
        acc_y: float,
        acc_z: float,
        /,
    ) -> None: ...
    def set_joint(
        self,
        index: int,
        position: float,
        velocity: float,
        torque: float,
        temperature: float,
        /,
    ) -> None: ...
    def joint(self, index: int, /) -> JointDataDict: ...
    def joints(self) -> list[JointDataDict]: ...
    def set_contact_force(self, index: int, force: float, /) -> None: ...
    def contact_force(self, index: int, /) -> float: ...
    def contact_forces(self) -> list[float]: ...
    def copy(self) -> RobotData: ...


class Timer:
    """Wrapper around the MotionSDK DRTimer."""

    def __init__(self, *, ms: int | None = None) -> None: ...
    def close(self) -> None: ...
    def init(self, ms: int, /) -> None: ...
    def interrupt(self) -> bool: ...
    def current_time(self) -> float: ...
    def interval_time(self, start_time: float, /) -> float: ...


class Sender:
    """UDP command sender for Lite3 joint commands."""

    def __init__(self, *, ip: str | None = None, port: int = 43893) -> None: ...
    def close(self) -> None: ...
    def send_cmd(self, cmd: RobotCmd, /) -> None: ...
    def control_get(self, mode: int, /) -> None: ...
    def return_control(self) -> None: ...
    def request_sdk_control(self) -> None: ...
    def all_joint_back_zero(self) -> None: ...
    def robot_state_init(self) -> None: ...
    def set_cmd(self, code: int, value: int, /) -> None: ...


class Receiver:
    """UDP receiver for Lite3 robot-state packets."""

    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def start_work(self) -> None: ...
    def register_update_flag(self) -> None: ...
    def message_updated(self) -> bool: ...
    def clear_update_flag(self) -> None: ...
    def get_state(self) -> RobotData: ...


class Command:
    """Wrapper around the SDK Command object."""

    def __init__(self, code: int, /, *, value: int | None = None, parameters: bytes | None = None) -> None: ...
    def close(self) -> None: ...
    def code(self) -> int: ...
    def value(self) -> int: ...
    def parameters_size(self) -> int: ...
    def parameters(self) -> bytes: ...


def cubic_spline(
    init_position: float,
    init_velocity: float,
    goal_position: float,
    goal_velocity: float,
    run_time: float,
    cycle_time: float,
    total_time: float,
    /,
) -> tuple[float, float, float]: ...

def record_initial_data(data: RobotData, time: float, /) -> None: ...
def pre_stand_up(cmd: RobotCmd, time: float, data: RobotData, /) -> None: ...
def stand_up(cmd: RobotCmd, time: float, data: RobotData, /) -> None: ...
